Resolve linker error due to undefined reference to 'clock_gettime' function. This function is part of the POSIX library and require linking against the real-time library, '-lrt'. Linker flag was added to the Makefile.